dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3"
matrix:
  include:
  - python: 3.8
    dist: xenial
  - python: 3.9
    dist: xenial
  - python: pypy
    dist: xenial
  - python: pypy3
    dist: xenial
services: mongodb
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pip install coveralls; fi
script: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage run --source=shopdesk setup.py test; else python setup.py test; fi
after_success: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coveralls; fi
deploy:
  provider: pypi
  user: joamag
  password:
    secure: L0eKn6FJitnxytSA4VlGouSMvr1kSX/hKVxFbS1T+22BuvZ1mgigLnFVSGGzJxM8kgXv0mDi5sbso1cYR070jD6o4qdNZm5YoAuTckZIaMrnZ0ACwtfWkX4t0xMGwQirG9szWlrX6NIJXL2pLNVkfT9LM/ggf+q2BNcYe51zy80=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
