dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy-5.4.1"
  - "pypy-5.6.0"
  - "pypy-5.7.1"
  - "pypy2.7-5.8.0"
  - "pypy2.7-5.9.0"
  - "pypy3.5-5.8.0"
  - "pypy3.5-5.9.0"
matrix:
  include:
  - python: 3.7
    dist: xenial
  - python: 3.8
    dist: xenial
  - python: pypy
    dist: xenial
  - python: pypy3
    dist: xenial
services: mongodb
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: coverage run --source=shopdesk setup.py test
after_success: coveralls
deploy:
  provider: pypi
  user: joamag
  password:
    secure: L0eKn6FJitnxytSA4VlGouSMvr1kSX/hKVxFbS1T+22BuvZ1mgigLnFVSGGzJxM8kgXv0mDi5sbso1cYR070jD6o4qdNZm5YoAuTckZIaMrnZ0ACwtfWkX4t0xMGwQirG9szWlrX6NIJXL2pLNVkfT9LM/ggf+q2BNcYe51zy80=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
