FROM ubuntu:latest
MAINTAINER Hive Solutions

EXPOSE 8080

ENV LEVEL INFO
ENV SERVER netius
ENV SERVER_ENCODING gzip
ENV HOST 0.0.0.0
ENV PORT 8080
ENV FORCE_SSL 1
ENV MONGOHQ_URL mongodb://localhost:27017
ENV SENDER_EMAIL "Shopdesk <no-reply@shopdesk.com>"
ENV SMTP_HOST SMTP_HOST
ENV SMTP_PORT 25
ENV SMTP_SSL 1
ENV SMTP_HELO_HOST SMTP_HELO_HOST
ENV SMTP_USER SMTP_USER
ENV SMTP_PASSWORD SMTP_PASSWORD
ENV SHOPIFY_API_KEY SHOPIFY_API_KEY
ENV SHOPIFY_PASSWORD SHOPIFY_PASSWORD
ENV SHOPIFY_SECRET SHOPIFY_SECRET
ENV SHOPIFY_STORE SHOPIFY_STORE
ENV EASYPAY_PRODUCTION 1
ENV EASYPAY_CIN EASYPAY_CIN
ENV EASYPAY_ENTITY EASYPAY_ENTITY
ENV EASYPAY_USERNAME EASYPAY_USERNAME
ENV EASYPAY_PATH easypay.shelve
ENV PYTHONPATH /src

ADD requirements.txt /
ADD extra.txt /
ADD src /src

RUN apt-get update && apt-get install -y -q python python-setuptools python-dev python-pip
RUN pip install -r /requirements.txt && pip install -r /extra.txt && pip install --upgrade netius

CMD python /src/shopdesk/main.py
